name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update version numbers
      run: |
        git checkout ${{ github.ref }}
        Get-ChildItem -Directory | ForEach-Object {
            cd $_.Name
            (Get-Content project.json | ForEach-Object { $_ -replace "0.0.0", "${{github.ref}}" }) | Set-Content project.json
            cd ..
        }
    - name: Build and create nuget packages
      run: |
        Get-ChildItem -Directory | ForEach-Object {
            cd $_.Name
            dotnet build -c Release
            dotnet pack -c Release
            cd ..
        }
    - name: Publish packages
      run: |
        Get-ChildItem -Directory | ForEach-Object {
            cd $_.Name
            nuget push *.nupkg -Source https://nuget.pkg.github.com/jeremyregnerus/index.json -ApiKey ${{secrets.PACKAGE_API_KEY}}
            cd ..
        }
