name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update version numbers
      run: |
        git checkout ${{ github.ref }}
        for ($dir in (Get-ChildItem -Directory)) {
            cd $dir
            (Get-Content project.json | ForEach-Object { $_ -replace "0.0.0", "${{github.ref}}" }) | Set-Content project.json
            cd ..
        }
    - name: Build and create nuget packages
      run: |
        for ($dir in (Get-ChildItem -Directory)) {
            cd $dir
            dotnet build -c Release
            dotnet pack -c Release
            cd ..
        }
    - name: Publish packages
      run: |
        for ($dir in (Get-ChildItem -Directory)) {
            cd $dir
            nuget push *.nupkg -Source https://nuget.pkg.github.com/OWNER/index.json -ApiKey ${{secrets.PACKAGE_API_KEY}}
            cd ..
        }
