name: Nuget Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release

    - name: Deploy
      run: nuget push **/JSR.Asserts/bin/Release/JSR.Asserts.`tag`.nupkg --api-key ${{ secrets.PACKAGE_API_KEY }} -s "https://nuget.pkg.github.com/jeremyregnerus/index.json"
