name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update version numbers
      run: |
        git checkout ${{ github.ref }}
        Get-ChildItem -Directory | ForEach-Object {
            cd $_.Name
            (Get-Content *.csproj -Raw) -replace '<Version>0.0.0</Version>', "<Version>${{github.ref}}</Version>" | Set-Content *.csproj
            cd ..
        }
    - name: Build and create nuget packages
      run: |
        Get-ChildItem -Directory | ForEach-Object {
            cd $_.Name
            if (Test-Path .\*.nuspec) {
                dotnet build -c Release
                dotnet pack -c Release
            }
            cd ..
        }
    - name: Publish packages
      run: |
        Get-ChildItem -Directory | ForEach-Object {
            cd $_.Name
            if (Test-Path .\*.nuspec) {
                nuget push *.nupkg -Source https://nuget.pkg.github.com/jeremyregnerus/index.json -ApiKey ${{secrets.PACKAGE_API_KEY}}
            }
            cd ..
        }