
name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update version numbers
      run: |
        git checkout ${{ github.ref }}
        $projects = @("JSR.Asserts", "JSR.BaseClasses", "JSR.Converters", "JSR.Serialization", "JSR.Utilities")
        foreach ($project in $projects) {
            cd $project
            $current_version = (Select-Xml -Path *.csproj -XPath "//*[local-name()='Version']/text()").Node.Value
            (Get-Content *.csproj -Raw) -replace $current_version, "${{github.ref}}" | Set-Content *.csproj
            cd ..
        }
    - name: Build and create nuget packages
      run: |
        foreach ($project in $projects) {
            cd $project
            if (Test-Path .\*.nuspec) {
                dotnet build -c Release
                dotnet pack -c Release
            }
            cd ..
        }
    - name: Publish packages
      run: |
        foreach ($project in $projects) {
            cd $project
            if (Test-Path .\*.nuspec) {
                nuget push *.nupkg -Source https://nuget.pkg.github.com/jeremyregnerus/index.json -ApiKey ${{secrets.PACKAGE_API_KEY}}
            }
            cd ..
        }
